CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(100) NOT NULL,
                      author VARCHAR(50) NOT NULL
);
